Add support for GW
JetBrains/gradle-intellij-plugin pull request #744
Opened 2021-07-15 19:29 UTC by abrooksv

2021-07-16 09:38 UTC, zolotov requested changes

2021-07-16 09:38 UTC, zolotov commented on src/main/kotlin/org/jetbrains/intellij/utils.kt
> +        BUILD_VERSION_PATTERN.matcher(version).matches()
this one is not good. I think it breaks nightly IDEA builds, that look like `201.1463-SNAPSHOT` and must be downloaded from `nightly` repo. 
GW should be either uploaded to `nightly` (access from JB network only), or to be renamed, e.g. with `-CUSTOM-SNAPSHOT` prefix (I cannot remember why we introduced it, though).

2021-07-16 13:38 UTC, shalupov commented
I merged maven coordinates as https://github.com/JetBrains/gradle-intellij-plugin/commit/5f078a51d433cad10e37331ae5c49df76af74682

As for other changes we discussed with @zolotov how not to do them at all.
So, support for JetBrains Gateway and any future product will be added around next week

2021-07-16 13:38 UTC, closed without merging

2021-07-19 14:38 UTC, zolotov commented
see https://github.com/JetBrains/gradle-intellij-plugin/pull/746. Going to include that in 1.1.4